### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by Keith94** [CookiePLMonster/SilentPatchMGR#1]
Will there be a resolution/aspect ratio hack, frame rate unlock, etc.?

**Comment by CookiePLMonster** [comment]
> resolution/aspect ratio hack

I kinda want to, but so far I checked the code very briefly and it seems like they **might** have hardcoded resolution specific stuff into this set of available resolutions, so if this is the case then it'll likely be way too much work (and too error prone potentially).



> frame rate unlock

Probably not, unless it's easy and doesn't break the game.

**Comment by Keith94** [comment]
OK, I'll wait and see what gets implemented or not!
